<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Model;

class PurchaseOrders extends Model
{
    use HasFactory;

    protected $table = 'purchase_orders';

    protected $fillable = [
        'comCode',
        'documentID',
        'documentDate',
        'bound',
        'freight',
        'port_of_landing',
        'co',
        'paperless',
        'etdDate',
        'etaDate',
        'closingDate',
        'invNo',
        'bill',
        'bookingNo',
        'deliveryType',
        'saleman',
        'cusCode',
        'cusContact',
        'agentCode',
        'agentContact',
        'feeder',
        'vessel',
        'note',
        'stu_location',
        'stu_contact',
        'stu_mobile',
        'stu_date',
        'cy_location',
        'cy_contact',
        'cy_mobile',
        'cy_date',
        'rtn_location',
        'rtn_contact',
        'rtn_mobile',
        'rtn_date',
        'good_total_num_package',
        'good_commodity',
        'billOfladingNo',
        'trailer_bookingNO',
        'fob',
        'place_receive',
        'documentstatus',
        'createID',
        'createTime',
        'editID',
        'editTime',
    ];

    protected $casts = [
        'comCode' => 'string',
        'documentID' => 'string',
        'documentDate' => 'date: Y-m-d',
        'bound' => 'string',
        'freight' => 'string',
        'port_of_landing' => 'string',
        'co' => 'string',
        'paperless' => 'string',
        'etdDate' => 'date: Y-m-d',
        'etaDate' => 'date: Y-m-d',
        'closingDate' => 'date: Y-m-d',
        'invNo' => 'string',
        'bill' => 'string',
        'bookingNo' => 'string',
        'deliveryType' => 'string',
        'saleman' => 'string',
        'cusCode' => 'string',
        'cusContact' => 'string',
        'agentCode' => 'string',
        'agentContact' => 'string',
        'feeder' => 'string',
        'vessel' => 'string',
        'note' => 'string',
        'stu_location' => 'string',
        'stu_contact' => 'string',
        'stu_mobile' => 'string',
        'stu_date' => 'date: Y-m-d',
        'cy_location' => 'string',
        'cy_contact' => 'string',
        'cy_mobile' => 'string',
        'cy_date' => 'date: Y-m-d',
        'rtn_location' => 'string',
        'rtn_contact' => 'string',
        'rtn_mobile' => 'string',
        'rtn_date' => 'date: Y-m-d',
        'good_total_num_package' => 'string',
        'good_commodity' => 'string',
        'billOfladingNo' => 'string',
        'trailer_bookingNO' => 'string',
        'fob' => 'string',
        'place_receive' => 'string',
        'documentstatus' => 'string',
        'createID' => 'string',
        'createTime' => 'datetime:Y-m-d H:M',
        'editID' => 'string',
        'editTime' => 'datetime:Y-m-d H:M',
    ];
}
